version: "3.8"

services:
  twitch-downloader:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: twitch-vod-downloader
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    env_file:
      - .env
    volumes:
      - ./data:/workspace/data
    command: ["deno", "task", "start"]